# AVISO: Qualquer mudança feita neste arquivo será perdida quando o pyuic5 for executado novamente.
# Não edite este arquivo a menos que você saiba o que está fazendo.
# Arquivo convertido em ui2py.vercel.app

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuperbBiblioteca(object):
    def setupUi(self, SuperbBiblioteca):
        SuperbBiblioteca.setObjectName("SuperbBiblioteca")
        SuperbBiblioteca.resize(870, 571)
        SuperbBiblioteca.setMinimumSize(QtCore.QSize(870, 571))
        SuperbBiblioteca.setMaximumSize(QtCore.QSize(870, 571))
        SuperbBiblioteca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone site/images/icone site.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SuperbBiblioteca.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SuperbBiblioteca)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0597015, y1:0.08, x2:0.93, y2:0.886, stop:0 rgba(21, 24, 48, 255), stop:1 rgba(199, 19, 15, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 468))
        self.frame_3.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.585227, x2:1, y2:0.574136, stop:0.223881 rgba(25, 28, 41, 255), stop:0.293532 rgba(27, 29, 53, 227), stop:0.58209 rgba(27, 29, 53, 227), stop:0.651741 rgba(97, 30, 21, 255));")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame2_pag2 = QtWidgets.QFrame(self.frame_3)
        self.frame2_pag2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame2_pag2.setStyleSheet("background-color: rgb(35, 30, 52);\n"
"border-radius: 30px;")
        self.frame2_pag2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2_pag2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2_pag2.setObjectName("frame2_pag2")
        self.frame1_pag2 = QtWidgets.QFrame(self.frame2_pag2)
        self.frame1_pag2.setGeometry(QtCore.QRect(0, 0, 175, 561))
        self.frame1_pag2.setMaximumSize(QtCore.QSize(175, 16777215))
        self.frame1_pag2.setAutoFillBackground(False)
        self.frame1_pag2.setStyleSheet("background-color: rgb(25, 28, 41);\n"
"border-radius: 30px;")
        self.frame1_pag2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1_pag2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1_pag2.setObjectName("frame1_pag2")
        self.iconPerfil_pag3 = QtWidgets.QLabel(self.frame1_pag2)
        self.iconPerfil_pag3.setGeometry(QtCore.QRect(45, 60, 81, 81))
        self.iconPerfil_pag3.setStyleSheet("border-radius: 40px;\n"
"background-image: url(:/Perfil/images/iconPerfil_pag2.png);")
        self.iconPerfil_pag3.setText("")
        self.iconPerfil_pag3.setObjectName("iconPerfil_pag3")
        self.labelNome_pag3 = QtWidgets.QLabel(self.frame1_pag2)
        self.labelNome_pag3.setGeometry(QtCore.QRect(0, 170, 171, 20))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelNome_pag3.setFont(font)
        self.labelNome_pag3.setStyleSheet("color: rgb(175, 54, 38);")
        self.labelNome_pag3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNome_pag3.setObjectName("labelNome_pag3")
        self.botaoInicio_pag3 = QtWidgets.QPushButton(self.frame1_pag2)
        self.botaoInicio_pag3.setGeometry(QtCore.QRect(22, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(9)
        self.botaoInicio_pag3.setFont(font)
        self.botaoInicio_pag3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoInicio_pag3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(25, 28, 41);\n"
"    border: 2px solid rgb(35, 30, 52);\n"
"    border-radius: 5px;\n"
"    color: rgb(108, 83, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(35, 30, 52);\n"
"    border: 2px solid rgb(175, 54, 38);\n"
"    color: rgb(175, 54, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rbg(250, 270, 200);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    color: rgb(219, 149, 121);\n"
"}")
        self.botaoInicio_pag3.setObjectName("botaoInicio_pag3")
        self.labelIMG1 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMG1.setGeometry(QtCore.QRect(210, 40, 85, 85))
        self.labelIMG1.setStyleSheet("border-radius: 1px;\n"
"")
        self.labelIMG1.setText("")
        self.labelIMG1.setObjectName("labelIMG1_pag3")
        self.labelIMG2 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMG2.setGeometry(QtCore.QRect(210, 168, 85, 85))
        self.labelIMG2.setStyleSheet("border-radius: 1px;")
        self.labelIMG2.setText("")
        self.labelIMG2.setObjectName("labelIMG2_pag3")
        self.labelIMG3 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMG3.setGeometry(QtCore.QRect(210, 296, 85, 85))
        self.labelIMG3.setStyleSheet("border-radius: 1px;")
        self.labelIMG3.setText("")
        self.labelIMG3.setObjectName("labelIMG3_pag3")
        self.labelIMG4 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMG4.setGeometry(QtCore.QRect(210, 424, 85, 85))
        self.labelIMG4.setStyleSheet("border-radius: 1px;")
        self.labelIMG4.setText("")
        self.labelIMG4.setObjectName("labelIMG4_pag3")
        self.labelnome1 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelnome1.setGeometry(QtCore.QRect(320, 45, 221, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelnome1.setFont(font)
        self.labelnome1.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelnome1.setText("")
        self.labelnome1.setObjectName("labelnome1_pag3")
        self.labeltextavaliar1 = QtWidgets.QLabel(self.frame2_pag2)
        self.labeltextavaliar1.setGeometry(QtCore.QRect(320, 80, 261, 18))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labeltextavaliar1.setFont(font)
        self.labeltextavaliar1.setStyleSheet("color: rgb(255, 230, 219);")
        self.labeltextavaliar1.setText("")
        self.labeltextavaliar1.setObjectName("labeltempo1_pag3")
        self.labelIMGjoinha1 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMGjoinha1.setGeometry(QtCore.QRect(610, 40, 41, 41))
        self.labelIMGjoinha1.setStyleSheet("")
        self.labelIMGjoinha1.setText("")
        self.labelIMGjoinha1.setObjectName("label_7")
        self.labeltextavaliar2 = QtWidgets.QLabel(self.frame2_pag2)
        self.labeltextavaliar2.setGeometry(QtCore.QRect(320, 208, 261, 18))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labeltextavaliar2.setFont(font)
        self.labeltextavaliar2.setStyleSheet("color: rgb(255, 230, 219);")
        self.labeltextavaliar2.setText("")
        self.labeltextavaliar2.setObjectName("labeltempo2_pag3")
        self.labelnome2 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelnome2.setGeometry(QtCore.QRect(320, 173, 221, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelnome2.setFont(font)
        self.labelnome2.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelnome2.setText("")
        self.labelnome2.setObjectName("labelnome2_pag3")
        self.labelIMGjoinha2 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMGjoinha2.setGeometry(QtCore.QRect(610, 168, 41, 41))
        self.labelIMGjoinha2.setStyleSheet("")
        self.labelIMGjoinha2.setText("")
        self.labelIMGjoinha2.setObjectName("label_13")
        self.labelnome3 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelnome3.setGeometry(QtCore.QRect(320, 301, 221, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelnome3.setFont(font)
        self.labelnome3.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelnome3.setText("")
        self.labelnome3.setObjectName("labelnome3_pag3")
        self.labelIMGjoinha3 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMGjoinha3.setGeometry(QtCore.QRect(610, 296, 41, 41))
        self.labelIMGjoinha3.setStyleSheet("")
        self.labelIMGjoinha3.setText("")
        self.labelIMGjoinha3.setObjectName("label_18")
        self.labeltextavaliar3 = QtWidgets.QLabel(self.frame2_pag2)
        self.labeltextavaliar3.setGeometry(QtCore.QRect(320, 336, 261, 18))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labeltextavaliar3.setFont(font)
        self.labeltextavaliar3.setStyleSheet("color: rgb(255, 230, 219);")
        self.labeltextavaliar3.setText("")
        self.labeltextavaliar3.setObjectName("labeltempo3_pag3")
        self.labelIMGjoinha4 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelIMGjoinha4.setGeometry(QtCore.QRect(610, 424, 41, 41))
        self.labelIMGjoinha4.setStyleSheet("")
        self.labelIMGjoinha4.setText("")
        self.labelIMGjoinha4.setObjectName("label_23")
        self.labeltextavaliar4 = QtWidgets.QLabel(self.frame2_pag2)
        self.labeltextavaliar4.setGeometry(QtCore.QRect(320, 464, 261, 18))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labeltextavaliar4.setFont(font)
        self.labeltextavaliar4.setStyleSheet("color: rgb(255, 230, 219);")
        self.labeltextavaliar4.setText("")
        self.labeltextavaliar4.setObjectName("labeltempo4_pag3")
        self.labelnome4 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelnome4.setGeometry(QtCore.QRect(320, 429, 221, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelnome4.setFont(font)
        self.labelnome4.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelnome4.setText("")
        self.labelnome4.setObjectName("labelnome4_pag3")
        self.botaoDescer_pag3 = QtWidgets.QPushButton(self.frame2_pag2)
        self.botaoDescer_pag3.setGeometry(QtCore.QRect(720, 490, 51, 51))
        self.botaoDescer_pag3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoDescer_pag3.setStyleSheet("QPushButton {\n"
"    image: url(:/Setas/images/DownArrow-TextEdit_pag3.png);\n"
"}")
        self.botaoDescer_pag3.setText("")
        self.botaoDescer_pag3.setObjectName("botaoDescer_pag3")
        self.labelhorasjogadas1 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelhorasjogadas1.setGeometry(QtCore.QRect(320, 105, 191, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelhorasjogadas1.setFont(font)
        self.labelhorasjogadas1.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelhorasjogadas1.setText("")
        self.labelhorasjogadas1.setObjectName("labelhorasjogadas1")
        self.labelhorasjogadas2 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelhorasjogadas2.setGeometry(QtCore.QRect(320, 233, 191, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelhorasjogadas2.setFont(font)
        self.labelhorasjogadas2.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelhorasjogadas2.setText("")
        self.labelhorasjogadas2.setObjectName("labelhorasjogadas2")
        self.labelhorasjogadas3 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelhorasjogadas3.setGeometry(QtCore.QRect(320, 361, 191, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelhorasjogadas3.setFont(font)
        self.labelhorasjogadas3.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelhorasjogadas3.setText("")
        self.labelhorasjogadas3.setObjectName("labelhorasjogadas3")
        self.labelhorasjogadas4 = QtWidgets.QLabel(self.frame2_pag2)
        self.labelhorasjogadas4.setGeometry(QtCore.QRect(320, 489, 191, 16))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelhorasjogadas4.setFont(font)
        self.labelhorasjogadas4.setStyleSheet("color: rgb(255, 230, 219);")
        self.labelhorasjogadas4.setText("")
        self.labelhorasjogadas4.setObjectName("labelhorasjogadas4")
        self.horizontalLayout.addWidget(self.frame2_pag2)
        self.frame3_pag2 = QtWidgets.QFrame(self.frame_3)
        self.frame3_pag2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame3_pag2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame3_pag2.setStyleSheet("background-color: rgb(97, 30, 21);")
        self.frame3_pag2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_pag2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_pag2.setObjectName("frame3_pag2")
        self.botaoVoltarLog_pag3 = QtWidgets.QPushButton(self.frame3_pag2)
        self.botaoVoltarLog_pag3.setGeometry(QtCore.QRect(4, 402, 61, 61))
        self.botaoVoltarLog_pag3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoVoltarLog_pag3.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(97,30, 21);\n"
"    background-image: url(:/Login/images/casa_login_pag2.png);\n"
"    border-radius: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/Login/images/casa_login_hover_pag2.png);\n"
"    background-color: rgb(84, 26, 18);\n"
"    border: 2px solid rgb(84, 26, 18);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(141, 44, 31);\n"
"    border: 2px solid rgb(141, 44, 31);\n"
"}")
        self.botaoVoltarLog_pag3.setText("")
        self.botaoVoltarLog_pag3.setObjectName("botaoVoltarLog_pag3")
        self.botaoSair_pag3 = QtWidgets.QPushButton(self.frame3_pag2)
        self.botaoSair_pag3.setGeometry(QtCore.QRect(4, 470, 61, 61))
        self.botaoSair_pag3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoSair_pag3.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(97,30, 21);\n"
"    border-radius: 30px;\n"
"    background-image: url(:/Sair/images/sair_pag2.png);\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/Sair/images/sair_hover_pag2.png);\n"
"    background-color: rgb(84, 26, 18);\n"
"    border: 2px solid rgb(84, 26, 18);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(141, 44, 31);\n"
"    border: 2px solid rgb(141, 44, 31);\n"
"}")
        self.botaoSair_pag3.setText("")
        self.botaoSair_pag3.setObjectName("botaoSair_pag3")
        self.iconSuperb_pag2 = QtWidgets.QLabel(self.frame3_pag2)
        self.iconSuperb_pag2.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.iconSuperb_pag2.setStyleSheet("image: url(:/Icone Site/images/icone site.png);")
        self.iconSuperb_pag2.setText("")
        self.iconSuperb_pag2.setObjectName("iconSuperb_pag2")
        self.horizontalLayout.addWidget(self.frame3_pag2)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame)
        SuperbBiblioteca.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SuperbBiblioteca)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 26))
        self.menubar.setObjectName("menubar")
        SuperbBiblioteca.setMenuBar(self.menubar)

        self.retranslateUi(SuperbBiblioteca)
        self.botaoSair_pag3.clicked.connect(SuperbBiblioteca.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SuperbBiblioteca)

    def retranslateUi(self, SuperbBiblioteca):
        _translate = QtCore.QCoreApplication.translate
        SuperbBiblioteca.setWindowTitle(_translate("SuperbBiblioteca", "MainWindow"))
        self.labelNome_pag3.setText(_translate("SuperbBiblioteca", "*"))
        self.botaoInicio_pag3.setText(_translate("SuperbBiblioteca", "Início"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SuperbBiblioteca = QtWidgets.QMainWindow()
    ui = Ui_SuperbBiblioteca()
    ui.setupUi(SuperbBiblioteca)
    SuperbBiblioteca.show()
    sys.exit(app.exec_())
